context:
  name: autogen-core
  version: 0.4.2
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name|replace("-","_") }}/${{ name|replace("-","_") }}-${{ version }}.tar.gz
  sha256: 14b735a8eb76540014187c0051e0f22d72d4e683017b08285be76746defc7125

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
  - python >=${{ python_min }},<3.13
  - pip
  - hatchling
  run:
  - python >=${{ python_min }},<3.13
  - pillow >=11.0.0
  - typing-extensions >=4.0.0
  - pydantic >=2.10.0,<3.0.0
  - protobuf >=4.25.1,<4.25.2
  - opentelemetry-api >=1.27.0
  - jsonref >=1.1.0,<1.1.1

tests:
  - python:
      imports:
      - autogen_core
      pip_check: true

about:
  homepage: https://github.com/microsoft/autogen/tree/main/python/packages/autogen-core
  summary: Foundational interfaces and agent runtime implementation for AutoGen
  license: MIT
  license_file: LICENSE-CODE
  documentation: https://microsoft.github.io/autogen/stable/user-guide/core-user-guide/index.html
  repository: https://github.com/microsoft/autogen

extra:
  recipe-maintainers:
  - specter119
