context:
  name: autogen-core
  version: "0.6.4"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name|replace("-","_") }}/${{ name|replace("-","_") }}-${{ version }}.tar.gz
  sha256: 0c0ea2aa2794d5ec28e55eb2385480761e591f07c34dbd814feb71a21407aa0d

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }},<3.13
    - pillow >=11.0.0
    - typing-extensions >=4.0.0
    - pydantic >=2.10.0,<3.0.0
    - protobuf >=5.29.3,<5.30.dev0
    - opentelemetry-api >=1.34.1
    - jsonref >=1.1.0,<1.2.dev0

tests:
  - python:
      imports:
        - autogen_core
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/microsoft/autogen/tree/main/python/packages/autogen-core
  summary: Foundational interfaces and agent runtime implementation for AutoGen
  license: MIT
  license_file: LICENSE-CODE
  documentation: https://microsoft.github.io/autogen/stable/user-guide/core-user-guide/index.html
  repository: https://github.com/microsoft/autogen

extra:
  recipe-maintainers:
    - specter119
    - jan-janssen
